//-------------------------------------------------------------------------------
// Copyright (c) 2012 by Silicon Laboratories
// All rights reserved. This program and the accompanying materials
// are made available under the terms of the Silicon Laboratories End User
// License Agreement which accompanies this distribution, and is available at
// http://developer.silabs.com/legal/version/v10/License_Agreement_v10.htm
//
//
// Original content and implementation provided by Silicon Laboratories
//-------------------------------------------------------------------------------

//==============================================================================
// WARNING:
//
// This file is auto-generated by AppBuilder and should not be modified.
// Any hand modifications will be lost if the project is regenerated.
//==============================================================================


#include <SI32_PBCFG_A_Type.h>
#include <si32_device.h>
#include <SI32_PBSTD_A_Type.h>
#include <SI32_CLKCTRL_A_Type.h>

void pb_init_from_reset(void)
{
	SI32_CLKCTRL_A_enable_apb_to_modules_0(SI32_CLKCTRL_0, SI32_CLKCTRL_A_APBCLKG0_PB0);

	SI32_PBSTD_A_write_pbskipen(SI32_PBSTD_0, 0x0C3f);
	// PB0 Setup
//	SI32_PBSTD_A_write_pbskipen(SI32_PBSTD_0, 0x0C00);

	// PB1 Setup
	SI32_PBSTD_A_write_pbskipen(SI32_PBSTD_1, 0x00FF);

	// PB2 Setup
	SI32_PBSTD_A_write_pbskipen(SI32_PBSTD_2, 0xFF00);

	// PB3 Setup
	SI32_PBSTD_A_write_pbskipen(SI32_PBSTD_3, 0xFC00);

	// Enable Crossbar0 signals & set properties
	SI32_PBCFG_A_enable_crossbar_0(SI32_PBCFG_0);
}


